---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/lidarr:/config
      - /opt/lidarr/music:/music #optional
      - /opt/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: always
