apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: readarr
  name: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: readarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: readarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/London
          image: lscr.io/linuxserver/readarr:nightly
          name: readarr
          ports:
            - containerPort: 8787
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: readarr-claim0
            - mountPath: /books
              name: readarr-claim1
            - mountPath: /downloads
              name: readarr-claim2
      restartPolicy: Always
      volumes:
        - name: readarr-claim0
          persistentVolumeClaim:
            claimName: readarr-claim0
        - name: readarr-claim1
          persistentVolumeClaim:
            claimName: readarr-claim1
        - name: readarr-claim2
          persistentVolumeClaim:
            claimName: readarr-claim2
