---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/sonarr:/config
      - /opt/sonarr/tv:/tv #optional
      - /opt/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: always
