apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bazarr
  name: bazarr
spec:
  ports:
    - name: "6767"
      port: 6767
      targetPort: 6767
  selector:
    io.kompose.service: bazarr
