apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bazarr
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bazarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/bazarr:latest
          name: bazarr
          ports:
            - containerPort: 6767
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: bazarr-claim0
            - mountPath: /movies
              name: bazarr-claim1
            - mountPath: /tv
              name: bazarr-claim2
      restartPolicy: Always
      volumes:
        - name: bazarr-claim0
          persistentVolumeClaim:
            claimName: bazarr-claim0
        - name: bazarr-claim1
          persistentVolumeClaim:
            claimName: bazarr-claim1
        - name: bazarr-claim2
          persistentVolumeClaim:
            claimName: bazarr-claim2
