---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /opt/plex:/config
      - /opt/sonarr/tv:/tv
      - /opt/radarr/movies:/movies
    restart: always
