apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: plex
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plex
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: plex
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: VERSION
              value: docker
          image: lscr.io/linuxserver/plex
          name: plex
          volumeMounts:
            - mountPath: /config
              name: plex-claim0
            - mountPath: /tv
              name: plex-claim1
            - mountPath: /movies
              name: plex-claim2
      restartPolicy: Always
      volumes:
        - name: plex-claim0
          persistentVolumeClaim:
            claimName: plex-claim0
        - name: plex-claim1
          persistentVolumeClaim:
            claimName: plex-claim1
        - name: plex-claim2
          persistentVolumeClaim:
            claimName: plex-claim2
