apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: HOST_WHITELIST
            - name: PASS
            - name: PEERPORT
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TRANSMISSION_WEB_HOME
            - name: TZ
              value: Etc/UTC
            - name: USER
            - name: WHITELIST
          image: lscr.io/linuxserver/transmission:latest
          name: transmission
          ports:
            - containerPort: 9091
              protocol: TCP
            - containerPort: 51413
              protocol: TCP
            - containerPort: 51413
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: transmission-claim0
            - mountPath: /downloads
              name: transmission-claim1
      restartPolicy: Always
      volumes:
        - name: transmission-claim0
          persistentVolumeClaim:
            claimName: transmission-claim0
        - name: transmission-claim1
          persistentVolumeClaim:
            claimName: transmission-claim1
