apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nzbget
  name: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nzbget
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nzbget
    spec:
      containers:
        - env:
            - name: NZBGET_PASS
              value: tegbzn6789
            - name: NZBGET_USER
              value: nzbget
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/nzbget:latest
          name: nzbget
          ports:
            - containerPort: 6789
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: nzbget-claim0
            - mountPath: /downloads
              name: nzbget-claim1
      restartPolicy: Always
      volumes:
        - name: nzbget-claim0
          persistentVolumeClaim:
            claimName: nzbget-claim0
        - name: nzbget-claim1
          persistentVolumeClaim:
            claimName: nzbget-claim1
