all:
  children:
    kube-primary:
      hosts:
        192.168.0.188: # Change me
    kube:
      hosts:
        192.168.0.59: # Change me too once you have initialized the primary node
      children:
        kube-primary:
